[package]
name = "plover-pl-dict-gen-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.3"
indicatif = "0.17.2"
lazy_static = "1.4.0"
log = "0.4.17"
phf = {version = "0.11.1", features = ["macros"]}
regex = {version = "1.9.5"}
serde = "1.0.189"
serde_json = "1.0.107"

